// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Redis.Stu.Model;

namespace Redis.Stu.Model.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20181109114017_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Redis.Stu.Model.Data.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Course");

                    b.HasData(
                        new { ID = 1, CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), Name = "语文" },
                        new { ID = 2, CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), Name = "数学" },
                        new { ID = 3, CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), Name = "英语" },
                        new { ID = 4, CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), Name = "物理" }
                    );
                });

            modelBuilder.Entity("Redis.Stu.Model.Data.Grade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Grade");

                    b.HasData(
                        new { ID = 1, CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), Name = "一年级" },
                        new { ID = 2, CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), Name = "二年级" },
                        new { ID = 3, CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), Name = "三年级" }
                    );
                });

            modelBuilder.Entity("Redis.Stu.Model.Data.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("GradeId");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Remark");

                    b.Property<int>("Sex");

                    b.HasKey("ID");

                    b.HasIndex("GradeId");

                    b.ToTable("Student");

                    b.HasData(
                        new { ID = 1, Age = 20, Code = "sunquan", CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), GradeId = 1, Name = "孙权", Password = "000000", Sex = 1 },
                        new { ID = 2, Age = 20, Code = "liubei", CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), GradeId = 1, Name = "刘备", Password = "000000", Sex = 1 },
                        new { ID = 3, Age = 20, Code = "caocao", CreateTime = new DateTime(2018, 11, 9, 19, 40, 16, 829, DateTimeKind.Local), GradeId = 1, Name = "曹操", Password = "000000", Sex = 1 }
                    );
                });

            modelBuilder.Entity("Redis.Stu.Model.Data.StudentCourse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseID");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("StudentID");

                    b.HasKey("ID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentCourse");
                });

            modelBuilder.Entity("Redis.Stu.Model.Data.Student", b =>
                {
                    b.HasOne("Redis.Stu.Model.Data.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Redis.Stu.Model.Data.StudentCourse", b =>
                {
                    b.HasOne("Redis.Stu.Model.Data.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID");

                    b.HasOne("Redis.Stu.Model.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");
                });
#pragma warning restore 612, 618
        }
    }
}
